### ISSUE TITLE
We can do better than the linear search which runs in O(n).

### ISSUE THREAD

**Issue by DaleSeo** [LearnToCodeSeoul/pomodoro#6]

**Comment by mepda** [comment]
You mentioned that last night-- according to http://bigocheatsheet.com/ a hashtable is the way to go. I'm not sure if I fully grasp the workings of it, but I'll try to read up on it tonight/tomorrow morning!

**Comment by DaleSeo** [comment]
@mepda Sounds great. There was not enough time to tell you more about hashtables last night. In order to explain this, actually, I'd rather draw some stuff on a piece of paper because of the lack of my vocabulary in English. :cry: Let's talk a little bit about it tomorrow before we get going further.

**Comment by mepda** [comment]
I think this has been resolved
